# Generated by Django 4.2.5 on 2023-12-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbanao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='Role', max_length=8),
        ),
    ]
