# Generated by Django 4.2.5 on 2023-12-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbanao', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('mental health', 'Mental Health'), ('heart disease', 'Heart Disease'), ('covid19', 'Covid19'), ('immunization', 'Immunization')], default='Category', max_length=20),
        ),
    ]
