# Generated by Django 4.2.5 on 2024-01-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbanao', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photo/avatar.svg', null=True, upload_to='images/profile_photo'),
        ),
    ]
