# Generated by Django 4.2.5 on 2024-01-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbanao', '0008_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
